# Generated by Django 5.2.6 on 2025-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_en',
            field=models.TextField(null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_ru',
            field=models.TextField(null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_uz',
            field=models.TextField(null=True, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_en',
            field=models.TextField(null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_ru',
            field=models.TextField(null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_uz',
            field=models.TextField(null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Recipe Title'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Recipe Title'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Recipe Title'),
        ),
    ]
